"""dsh session-log import tests, driven by a real trimmed capture.

Regenerated by hand from an actual ``npx dsh --profile headless`` run against Ollama-backed
``deepseek-r1:8b`` -- see ``tokenomics.importers.dsh`` for why the parser targets
``assistant/chunk`` records rather than ``step/end``.
"""

from __future__ import annotations

from pathlib import Path

from tokenomics.importers.dsh import (
    ImportResult,
    find_session_files,
    import_paths,
    parse_session,
    parse_session_file,
)

FIXTURES = Path(__file__).parent.parent / "fixtures"
SESSION_ID = "session-ede7a60f-b14b-4f5d-90b0-a3f48eb3db8e"


def test_parses_the_real_captured_turn():
    events = list(parse_session_file(FIXTURES / "dsh_session.jsonl"))
    assert len(events) == 1

    event = events[0]
    assert event.trace_id and event.span_id
    assert event.provider == "ollama"
    assert event.request_model == "deepseek-r1:8b"
    assert event.response_model == "deepseek-r1:8b"
    assert event.operation == "chat"

    # inputTokens=1307, no cache reported by Ollama -> input passes through unchanged.
    assert event.tokens.input == 1307
    assert event.tokens.output == 996
    assert event.tokens.cache_read == 0
    assert event.tokens.cache_write == 0
    assert event.tokens.is_consistent()

    assert event.attribution.project == "dsh"
    assert event.attribution.feature == "tokenomics"  # basename of cwd "/mnt/tokenomics"
    assert event.attribution.subject_id == SESSION_ID
    assert event.attribution.tags["dsh.turn"] == "1"
    assert event.attribution.tags["dsh.step"] == "1"
    assert event.attribution.tags["dsh.response_id"] == "chatcmpl-696"
    # depth 0 is the root session; the tag is only added when it is truthy.
    assert "dsh.delegation_depth" not in event.attribution.tags


def test_reimporting_the_same_file_yields_identical_ids():
    """The (trace_id, span_id) pair must be stable across a re-import for idempotency."""
    first = list(parse_session_file(FIXTURES / "dsh_session.jsonl"))
    second = list(parse_session_file(FIXTURES / "dsh_session.jsonl"))
    assert [(e.trace_id, e.span_id) for e in first] == [(e.trace_id, e.span_id) for e in second]


def test_different_sessions_never_collide_on_ids():
    events = list(parse_session_file(FIXTURES / "dsh_session.jsonl"))
    other = list(
        parse_session(
            [
                {"type": "session", "id": "session-OTHER", "cwd": "/mnt/tokenomics"},
                _request_header(),
                _usage_chunk(input_tokens=1307, output_tokens=996),
                _finish_chunk(),
            ]
        )
    )
    assert events[0].trace_id != other[0].trace_id
    assert events[0].span_id != other[0].span_id


def _request_header(provider: str = "ollama", model: str = "deepseek-r1:8b") -> dict:
    return {
        "type": "request/header",
        "time": 1000,
        "data": {"header": {"config": {"provider": provider, "model": model}}},
    }


def _usage_chunk(
    *,
    turn: int = 1,
    step: int = 1,
    time_ms: int = 2000,
    input_tokens: int = 100,
    output_tokens: int = 50,
    cache_read: int = 0,
    cache_write: int = 0,
    reasoning: int = 0,
) -> dict:
    usage = {"inputTokens": input_tokens, "outputTokens": output_tokens}
    if cache_read:
        usage["cacheReadTokens"] = cache_read
    if cache_write:
        usage["cacheWriteTokens"] = cache_write
    if reasoning:
        usage["reasoningTokens"] = reasoning
    return {
        "type": "assistant/chunk",
        "time": time_ms,
        "data": {"turn": turn, "step": step, "chunk": {"type": "usage", "usage": usage}},
    }


def _finish_chunk(
    *,
    turn: int = 1,
    step: int = 1,
    time_ms: int = 2001,
    provider: str = "ollama",
    model: str = "deepseek-r1:8b",
    response_id: str = "resp-1",
) -> dict:
    return {
        "type": "assistant/chunk",
        "time": time_ms,
        "data": {
            "turn": turn,
            "step": step,
            "chunk": {
                "type": "finish",
                "replayState": {
                    "response": {"provider": provider, "model": model, "responseId": response_id}
                },
            },
        },
    }


def test_cache_counts_fold_into_input_inclusively():
    """dsh reports disjoint counts -- the same asymmetry Anthropic has via the SDK.

    Getting this backwards understates a cache-heavy agent's input by most of its prompt.
    """
    records = [
        {"type": "session", "id": "s1", "cwd": "/x"},
        _request_header(),
        _usage_chunk(input_tokens=200, output_tokens=50, cache_read=700, cache_write=100),
        _finish_chunk(),
    ]
    (event,) = parse_session(records)
    assert event.tokens.input == 1000  # 200 uncached + 700 cache_read + 100 cache_write
    assert event.tokens.cache_read == 700
    assert event.tokens.cache_write == 100
    assert event.tokens.is_consistent()


def test_a_turn_with_no_usage_chunk_yields_nothing():
    """An errored or aborted turn (e.g. MISSING_CREDENTIAL) has no usage chunk at all.

    It must not be billed as a $0 guess -- it is simply not represented.
    """
    records = [
        {"type": "session", "id": "s1", "cwd": "/x"},
        _request_header(),
        {"type": "turn/end", "data": {"turn": 1, "reason": {"kind": "error"}}},
    ]
    assert list(parse_session(records)) == []


def test_retries_produce_distinct_events_with_distinct_span_ids():
    """A retried call emits its own usage/finish pair within the same (turn, step).

    Each attempt must be billed once, as its own event, not merged or dropped.
    """
    records = [
        {"type": "session", "id": "s1", "cwd": "/x"},
        _request_header(),
        _usage_chunk(input_tokens=10, output_tokens=5, time_ms=100),
        _finish_chunk(time_ms=101, response_id="attempt-1"),
        # llm/retry-started would appear here in a real log; irrelevant to parsing.
        _usage_chunk(input_tokens=10, output_tokens=5, time_ms=200),
        _finish_chunk(time_ms=201, response_id="attempt-2"),
    ]
    events = list(parse_session(records))
    assert len(events) == 2
    assert events[0].span_id != events[1].span_id
    assert events[0].trace_id == events[1].trace_id  # same session -> same trace
    assert [e.attribution.tags["dsh.response_id"] for e in events] == ["attempt-1", "attempt-2"]


def test_response_model_wins_over_request_model_when_present():
    """finish.replayState.response is what actually served the call."""
    records = [
        {"type": "session", "id": "s1", "cwd": "/x"},
        _request_header(provider="ollama", model="deepseek-r1:8b"),
        _usage_chunk(input_tokens=10, output_tokens=5),
        _finish_chunk(provider="ollama", model="deepseek-r1:14b"),  # served on a bigger model
    ]
    (event,) = parse_session(records)
    assert event.request_model == "deepseek-r1:8b"
    assert event.response_model == "deepseek-r1:14b"
    assert event.billing_model == "deepseek-r1:14b"


def test_delegation_depth_tags_subagent_sessions():
    records = [
        {"type": "session", "id": "s1", "cwd": "/x", "delegationDepth": 2},
        _request_header(),
        _usage_chunk(input_tokens=10, output_tokens=5),
        _finish_chunk(),
    ]
    (event,) = parse_session(records)
    assert event.attribution.tags["dsh.delegation_depth"] == "2"


def test_find_session_files_discovers_both_extensions(tmp_path: Path):
    (tmp_path / "a").mkdir()
    (tmp_path / "a" / "session.jsonl").write_text("{}\n")
    (tmp_path / "b").mkdir()
    (tmp_path / "b" / "session.jsonl.zstd").write_bytes(b"\x28\xb5\x2f\xfd")  # not read, just found
    found = find_session_files(tmp_path)
    assert {p.name for p in found} == {"session.jsonl", "session.jsonl.zstd"}


def test_import_paths_prices_events_and_counts_unpriced(engine):
    result = import_paths([FIXTURES / "dsh_session.jsonl"], engine)
    assert isinstance(result, ImportResult)
    assert result.sessions_read == 1
    assert result.events_accepted == 1
    # ollama/deepseek-r1:8b is self-hosted with no matching book entry -> UNPRICED, not guessed.
    assert result.events_unpriced == 1
    assert result.events[0].cost is None
